"""Usage example: lavoro-domestico-non-convivente (H501).

CCNL Lavoro Domestico - DOMINA/FIDALDO/ASSINDATCOLF (non conviventi).

Generated by scripts/docs/gen_contract_examples.py from the bundled data;
edit the generator, not this file.

Level C (middle of the level list), regular run of September 2026, full-time
permanent employment, a household employer, worker resident in Milan (region
IT-25, municipality F205), seniority recognised from 1 September 2026.

Domestic work: 40 weekly hours and 173 contributable hours in the month; the
household employer withholds no IRPEF.
"""

from datetime import date
from decimal import Decimal

from ccnl_engine import (
    EmployerProfile,
    Employment,
    Headcount,
    PayrollEngine,
    PayrollRun,
    PeriodFacts,
    PeriodInput,
)
from ccnl_engine.inputs import (
    ContributableHours,
    Permanent,
    SeniorityFact,
    SenioritySource,
    WeeklyHours,
)

CCNL = "lavoro-domestico-non-convivente.json"
LEVEL = "C"
SENIORITY = SeniorityFact.since(date(2026, 9, 1), SenioritySource.EMPLOYER_RECORDS)

engine = PayrollEngine.bundled()
result = engine.calculate_period(
    PeriodInput(
        run=PayrollRun.regular(year=2026, month=9),
        payment_date=date(2026, 9, 25),
        employment=Employment(
            ccnl_slug=CCNL,
            level_code=LEVEL,
            contract_type=Permanent(),
            seniority=SENIORITY,
            weekly_hours=WeeklyHours(40),
            full_time_weekly_hours=WeeklyHours(40),
        ),
        employer=EmployerProfile(headcount=Headcount(1)),
        facts=PeriodFacts(
            contributable_hours=ContributableHours(Decimal(173)),
            regione="IT-25",
            comune_belfiore="F205",
        ),
    )
)

issues = ", ".join(sorted(issue.code for issue in result.issues)) or "none"
blockers = ", ".join(sorted({b.code.value for b in result.blockers})) or "none"
readiness = engine.inspect_ruleset(CCNL.removesuffix(".json")).readiness
print(f"Gross:         {result.period_gross} EUR")
print(f"Contributions: {result.contribution_breakdown.employee} EUR")
print(f"IRPEF:         {result.tax_computation.ordinary_tax} EUR")
print(f"Net:           {result.period_net} EUR")
print(f"Payable:       {result.is_payable}")
print(f"Readiness:     {readiness}")
print(f"Blockers:      {blockers}")
print(f"Issues:        {issues}")
