"""Contract tests for ccnl_engine's public API surface.

These tests guard against accidental drift in __all__ and ensure that
every advertised name is importable.
"""

import ccnl_engine

EXPECTED_PUBLIC: frozenset[str] = frozenset({
    "AbsenceEvent",
    "Apprentice",
    "ArrearsEvent",
    "BilateralFundEvent",
    "BonusEvent",
    "CalculationDecision",
    "CalculationIssue",
    "CalculationStatus",
    "BlockerCode",
    "CoverageStatus",
    "Payability",
    "ResultAssurance",
    "LimitationStatus",
    "MissingRuleError",
    "ModelLimitation",
    "MonetaryImpact",
    "ResultBlocker",
    "EvidenceStatus",
    "RulesetIdentity",
    "CalendarOverride",
    "CalendarOverrideReason",
    "CapabilityCatalog",
    "CapabilityEntry",
    "CapabilityGap",
    "CapabilityImplementation",
    "CapabilityScope",
    "CcnlEngineError",
    "CcnlId",
    "ContractSummary",
    "EngineMode",
    "RulesetAssurance",
    "RulesetKind",
    "RulesetReadiness",
    "VerificationStatus",
    "ContributableHours",
    "ContributionHistory",
    "DataIntegrityError",
    "DecisionOrigin",
    "DeferredShortfall",
    "Dependent",
    "DependentRelationship",
    "EmployerActivity",
    "EmployerProfile",
    "Employment",
    "EmploymentPeriod",
    "EmploymentSector",
    "FamilyComposition",
    "FixedTerm",
    "ForeignTaxPaid",
    "FringeEvent",
    "Headcount",
    "HolidayWorkEvent",
    "InvalidInputError",
    "NightShiftEvent",
    "OpeningBalances",
    "OutOfScopeError",
    "OvertimeEvent",
    "OvertimeKind",
    "PayrollEngine",
    "PayrollRun",
    "PayrollRunId",
    "PeriodFacts",
    "PeriodInput",
    "PeriodResult",
    "PensionFundEnrolment",
    "PeriodState",
    "Permanent",
    "PriorYearTaxFacts",
    "ShortfallDeferralRequest",
    "RecoveryObligation",
    "RecoveryPlan",
    "RemittanceColumn",
    "RemittanceLine",
    "SeniorityFact",
    "SenioritySource",
    "ShiftWorkEvent",
    "SickLeaveEvent",
    "SicknessCaseEvent",
    "SubstituteTaxRegime",
    "TerminationTFREvent",
    "UnknownCcnlError",
    "UnknownLevelError",
    "UnsupportedTaxYearError",
    "SurtaxComponent",
    "SurtaxObligation",
    "WeeklyHours",
    "WelfareEvent",
    "WorkCalendar",
    "WorkEvent",
    "WorkerCategory",
    "YearInput",
    "YearResult",
    "engine_version",
    "get_ccnl",
    "search_ccnls",
})


def test_all_exact() -> None:
    """__all__ must match the expected set exactly — no more, no less."""
    assert set(ccnl_engine.__all__) == EXPECTED_PUBLIC


def test_all_names_resolve() -> None:
    """Every name in __all__ must be importable from ccnl_engine."""
    for name in ccnl_engine.__all__:
        assert hasattr(ccnl_engine, name), f"Missing from ccnl_engine: {name}"
